import Head from "next/head";
import "bootstrap/dist/css/bootstrap.css";
import "jquery";
import '../styles/globals.css'

const generateHsl = () => {
  const hue = Math.round(Math.random() * 255);
  const saturation = Math.round((Math.random() * (1 - 0.5) + 0.5) * 100);
  const lightness = Math.round((Math.random() * (0.7 - 0.25) + 0.25) * 100);

  return `hsl(${hue}, ${saturation}%, ${lightness}%)`;
};
const hsl = generateHsl();

function MyApp({Component, pageProps}) {
  return (
    <>
      <Head>
        <title>Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="page">
        <Component {...pageProps} />
      </div>
    </>
  );
}

export default MyApp;
